export enum CandidateActionTypes {
  SET_CANDIDATES = "SET_CANDIDATES",
  SET_CURRENT_CANDIDATE = "SET_CURRENT_CANDIDATE",
  RESET_CURRENT_CANDIDATE = "RESET_CURRENT_CANDIDATE",
  SHORTLIST_CANDIDATE = "SHORTLIST_CANDIDATE",
  REJECT_CANDIDATE = "REJECT_CANDIDATE",
  DELETE_FROM_SHORTLIST = "DELETE_FROM_SHORTLIST",
  DELETE_FROM_REJECTED = "DELETE_FROM_REJECTED",
}